//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Achilles.Codex.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CodexItemLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodexItemLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Achilles.Codex.Web.Resources.CodexItemLabels", typeof(CodexItemLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string AttributeInfo {
            get {
                return ResourceManager.GetString("AttributeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat skill.
        /// </summary>
        public static string CombatSkill {
            get {
                return ResourceManager.GetString("CombatSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head armor.
        /// </summary>
        public static string HeadArmor {
            get {
                return ResourceManager.GetString("HeadArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee weapon.
        /// </summary>
        public static string MeleeWeapon {
            get {
                return ResourceManager.GetString("MeleeWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc item.
        /// </summary>
        public static string MiscellaneousItem {
            get {
                return ResourceManager.GetString("MiscellaneousItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged weapon.
        /// </summary>
        public static string RangedWeapon {
            get {
                return ResourceManager.GetString("RangedWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule set.
        /// </summary>
        public static string RuleSet {
            get {
                return ResourceManager.GetString("RuleSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill feature.
        /// </summary>
        public static string SkillFeature {
            get {
                return ResourceManager.GetString("SkillFeature", resourceCulture);
            }
        }
    }
}
